title: Simon Pastor
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an LSE Government and History alumnus passionate about the intersection of Data and Politics/Policy! 
  <br><br>
  <a href="https://www.linkedin.com/in/simonpastor/">View My Linkedin Profile</a> 
  <br><br>
  <a href="https://twitter.com/the_simonpastor">Follow me on Twitter ğŸ¦</a>
  <br><br>
  <a href="https://simonpastor.substack.com">Check out my Substack ğŸ’­</a>
  <p> 2021 Â© Simon Pastor </p>
<link rel="stylesheet" href="style.css" type="text/css" />
  
theme: jekyll-theme-minimal
google_analytics: UA-192273691-1
